FROM nginx:latest

ARG BUILD_DATE
ARG VCS_REF

# The maintainer list
LABEL authors="Milton Leon <miltonleon86@gmail.com>"
LABEL org.label-schema.build-date=$BUILD_DATE
LABEL org.label-schema.vcs-ref=$VCS_REF

EXPOSE 80
